PySleuth:
  General:
    program-email: pynotifs.ashwin@gmail.com # E-Mail for the program
    admin-email: na19b001@smail.iitm.ac.in # E-Mail of Admin
    save-data-to: /home/ashwin/github.com/ashwin5059198/PySleuth

  Components:
    Active:
      keylogger: true
      process-monitor: true
      mouse-monitor: true

    Process-Monitor:
      log-every: 2 # in seconds
