General:
  control-mode: telegram # or email
  monitor-every: 3
  save-data-to: /tmp/pysleuth

Email:
  program-email: "pynotifs.ashwin@gmail.com"
  admin-email: "na19b001@smail.iitm.ac.in"

Telegram: null

Components:
  KeyLogger:
    enable: true

  Process-Monitor:
    enable: true
    log-every: 3

  Mouse-Monitor:
    enable: true
    # take screenshots on mouse clicks/release
    capture-on-activity: true

  Screen-Monitor:
    enable: true
    log-every: 5
